// <auto-generated />
using System;
using DungeonMaster.Library.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DungeonMaster.Library.Migrations
{
    [DbContext(typeof(DungeonContext))]
    partial class DungeonContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DungeonMaster.Library.GuildMaster", b =>
                {
                    b.Property<ulong>("Guild")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong?>("AdminitrationCategoryChannel")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong?>("AuditLogChannel")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong?>("TogglePowerChannel")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("Guild");

                    b.ToTable("GuildMasters");
                });
#pragma warning restore 612, 618
        }
    }
}
