// <auto-generated />
using System;
using DungeonMaster.Library.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DungeonMaster.Library.Migrations
{
    [DbContext(typeof(DungeonContext))]
    partial class DungeonContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DungeonMaster.Library.GuildMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<ulong?>("AdminitrationCategoryChannel")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong?>("AuditLogChannel")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong?>("Guild")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong?>("TogglePowerChannel")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("Guild");

                    b.ToTable("GuildMasters");
                });

            modelBuilder.Entity("DungeonMaster.Library.MessageReference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<ulong>("ChannelId")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("MessageId")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId", "MessageId");

                    b.ToTable("MessageReferences");
                });

            modelBuilder.Entity("DungeonMaster.Library.ReactMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("GuildMasterId")
                        .HasColumnType("int");

                    b.Property<int?>("MessageReferenceId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("GuildMasterId");

                    b.HasIndex("MessageReferenceId");

                    b.ToTable("ReactMenus");
                });

            modelBuilder.Entity("DungeonMaster.Library.ReactMenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Command")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Emote")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("ReactMenuId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReactMenuId");

                    b.ToTable("ReactMenuItems");
                });

            modelBuilder.Entity("DungeonMaster.Library.ReactMenu", b =>
                {
                    b.HasOne("DungeonMaster.Library.GuildMaster", "GuildMaster")
                        .WithMany("ReactMenus")
                        .HasForeignKey("GuildMasterId");

                    b.HasOne("DungeonMaster.Library.MessageReference", "MessageReference")
                        .WithMany()
                        .HasForeignKey("MessageReferenceId");
                });

            modelBuilder.Entity("DungeonMaster.Library.ReactMenuItem", b =>
                {
                    b.HasOne("DungeonMaster.Library.ReactMenu", "ReactMenu")
                        .WithMany("Items")
                        .HasForeignKey("ReactMenuId");
                });
#pragma warning restore 612, 618
        }
    }
}
